### ISSUE TITLE
Not updated in 2 weeks 

### ISSUE THREAD

**Issue by GingerDavex** [HaydenPWoods/radio-stream-to-spotify#5]
hey, 

i love you code and its one of my favourite playlist on spotify but it hasn't updated in 2 weeks. not sure if you were aware. 
![Screenshot 2022-07-29 222311](https://user-images.githubusercontent.com/110262454/181844889-9170b585-6034-45cd-87ec-7604859b4914.png)

**Comment by HaydenPWoods** [comment]
Glad you find the playlist useful. Thanks for the heads up - I've restarted it and it's working again now. It's a manual process starting it up, so whenever power goes out etc. I sometimes forget to start it up again...
