### ISSUE TITLE
Playlist / Now-playing URL

### ISSUE THREAD

**Issue by DannyBeanz** [HaydenPWoods/radio-stream-to-spotify#6]
Hi,

If you don't mind helping me out, how do I find the URL of the now playing feed?  Spcifically I'm looking for Radio X in the UK, but general pointers would be appreciated too...

Many thanks,
D

**Comment by HaydenPWoods** [comment]
Hi Danny, the script in this repo takes the now playing info reported by the audio stream, and polls the stream every X seconds until you stop it. So you can use a Radio X stream url - e.g. an official link that will work: http://media-ice.musicradio.com/RadioXUK or http://media-ice.musicradio.com/RadioXUKMP3.

e.g for the streams.txt, try adding the following line:

`radio-x@@@http://media-ice.musicradio.com:80/RadioXUK@@@latin1@@@StreamTitle='(.*)';S@@@-@@@0@@@YOUR_SPOTIFY_PLAYLIST_ID@@@0`

You can use any radio stream url, so long as it reports the now playing information correctly - some don't. And you'll need to note how it reports it, and update the lines in streams.txt accordingly - e.g separator, and whether artist is before track title. You can check that by opening the stream in VLC:

![image](https://github.com/user-attachments/assets/dcda1f62-c4b5-4bba-9283-b8bd2a6abba3)

A good source for UK links is [radiofeeds.uk](http://www.radiofeeds.co.uk/).

Hope that's useful,
Hayden

**Comment by DannyBeanz** [comment]
Thank you for your prompt reply 👍
