### ISSUE TITLE
More noob help requested....

### ISSUE THREAD

**Issue by DannyBeanz** [HaydenPWoods/radio-stream-to-spotify#7]
Hi, again!
I've taken the plunge and am trying to get your script to run on my Raspberry Pi.  I'm a complete noob with Python and Raspberry Pi so am trying to learn as I go.

I have created the tekcore.cfg file with the Client ID and Client Secret and Callback URI from my spotify app in the dev portal.

So far, so good...

When I run your script on the Pi, I see the following in my terminal window:
![2024-08-09 12_40_47-Window](https://github.com/user-attachments/assets/59930495-b3da-4abe-9e2c-78461f90183f)

Opening that up shows the following:
![image](https://github.com/user-attachments/assets/932107db-2a04-436a-aaea-18826be3e2b1)

When I open the URL, I see the following in the browser:
![image](https://github.com/user-attachments/assets/8502fbf8-7b52-4d82-879a-df8e13699c92)

If I manually add "&client_id=xxx" with xxx being my Spotify client ID, I am prompted for the redirect_uri which if I add in the same way as the client_id parameter (URL encoded or otherwise) I get the message: "response_type must be code or token"

I'm guessing I've missed a step or am doing something wrong but I have no clue what, and I would really appreciate some (more) guidance, if you have the time.

D

**Comment by HaydenPWoods** [comment]
Hi Danny - it's possible that Tekore is trying to open the browser and that's not behaving correctly through SSH terminal access? Maybe a quick sanity check that your config file matches the below - e.g. no quotes around the values - in case it's just not loading the variables:

> [DEFAULT]
> SPOTIFY_CLIENT_ID=your_id
> SPOTIFY_CLIENT_SECRET=your_secret
> SPOTIFY_REDIRECT_URI=your_uri

I use "http://www.example.com" for the URI for simplicity - probably a silly idea sending my tokens to a remote server :) - but it can be whatever you like.

If that file is correct, options are...
- (edit: much simpler method...) In this project's files, navigate to /spotify, and in _init_.py, edit the parameters for the call to tk.prompt_for_user_token and add additional parameter open_browser=False at the end, e.g.
- 

```
user_token = tk.prompt_for_user_token(*config,
                                      scope=[tk.scope.playlist_read_private,
                                             tk.scope.playlist_read_collaborative,
                                             tk.scope.playlist_modify_public,
                                             tk.scope.playlist_modify_private], open_browser=False)
```

- Try running the script with a GUI to see if the same issue occurs - either on your PC locally, or install an OS on the Pi and remote in with VNC and run it through a terminal.

Hope that's somewhat useful, sorry the steps are a bit of a pain..!

**Comment by DannyBeanz** [comment]
Printing the URL to the console worked a treat, thank you!

I've now noticed the error: 'Spotify' object has no attribute 'playlist_remove_indices' and belive it's related to this: https://github.com/felix-hilden/tekore/pull/322, just FYI.

Thank you for your help
